### PR TITLE
Expose subCommands to subclass and add @SubCommand.attribute()

### PR DESCRIPTION
**Pull request by Librazy**
and publish maven to maven-repo-dev

### CODE REVIEW

**Comment by RecursiveG** [comment]
How attributes can be used
and what they can be used for?

**Comment by Librazy** [comment]
For CommandReceivers who override onCommand or onTabComplete. They can store data inside SubCommand annotation and use them to provide command prasing or tab completion.

**Comment by RecursiveG** [comment]
Then this field seems like **plugin-specific** data.
And there's **no specification** for the string format.
Thus naming it as `attribute` can be **misleading**.
I suggest rename it to `data` or something.

**Comment by RecursiveG** [comment]
Also, if you have ideas about how TabCompletion can be implemented,
you can try working on #7

**Pull request merged**
